# Generated by Django 5.2.5 on 2025-08-31 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoCredito', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoVenta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodoPago', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalValorVenta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fechaVenta', models.DateTimeField(auto_now_add=True)),
                ('estadoVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.estadoventa')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='VentaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCuotas', models.PositiveBigIntegerField()),
                ('valorCuota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fechaInicioCredito', models.DateTimeField(auto_now_add=True)),
                ('fechaFinCredito', models.DateTimeField()),
                ('interesCredito', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saldoPendiente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('EstadoCredito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.estadocredito')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProducto', models.PositiveBigIntegerField()),
                ('precioVentaUnidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subTotalValorProducto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descuentoProducto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('totalValorVenta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MetodoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.metodopago')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
