from django.contrib import admin
from .models import Rol, Persona, Empleado, Proveedor, Producto, Cliente, Movimiento, Venta, VentaCredito, VentaProducto, TipoContrato, TipoDocumento, TipoMovimiento, TipoPersona, Estado, EstadoCredito, EstadoCivil, EstadoEmpleado, EstadoProducto, EstadoVenta, MetodoPago, Genero, Categoria, Nacionalidad, JornadaLaboral 
admin.site.register(Rol)
admin.site.register(Persona)
admin.site.register(Empleado)
admin.site.register(Proveedor)
admin.site.register(Producto)
admin.site.register(Cliente)
admin.site.register(Movimiento)
admin.site.register(Venta)
admin.site.register(VentaProducto)
admin.site.register(VentaCredito)
admin.site.register(TipoContrato)
admin.site.register(TipoMovimiento)
admin.site.register(TipoDocumento)
admin.site.register(TipoPersona)
admin.site.register(Estado)
admin.site.register(EstadoCivil)
admin.site.register(EstadoCredito)
admin.site.register(EstadoEmpleado)
admin.site.register(EstadoProducto)
admin.site.register(EstadoVenta)
admin.site.register(MetodoPago)
admin.site.register(Genero)
admin.site.register(Categoria)
admin.site.register(Nacionalidad)
admin.site.register(JornadaLaboral)
# Register your models here.
