# Generated by Django 5.2.5 on 2025-08-31 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoEmpleado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JornadaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornadaLaboral', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoContrato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField()),
                ('fechaContratacion', models.DateField()),
                ('salarioEmpleado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('epsEmpleado', models.CharField(max_length=100)),
                ('fotoEmpleado', models.ImageField(blank=True, null=True, upload_to='uploads/fotos_empleados/')),
                ('idEstadoCivil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.estadocivil')),
                ('idGenero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.genero')),
                ('idNacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.nacionalidad')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
                ('idEstadoEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.estadoempleado')),
                ('idJornadaLaboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.jornadalaboral')),
                ('idTipoContrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.tipocontrato')),
            ],
        ),
    ]
