# Generated by Django 5.2.5 on 2025-09-01 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoSanguineo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoSanguineo', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='idGrupoSanguineo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleados.gruposanguineo'),
            preserve_default=False,
        ),
    ]
