# Generated by Django 5.2.5 on 2025-09-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_gruposanguineo_empleado_idgruposanguineo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='idGenero',
        ),
    ]
