# Generated by Django 5.2.5 on 2025-08-29 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreCategoria", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EstadoCivil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estadoCivil", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EstadoCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estadoCredito", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EstadoEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estadoEmpleado", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EstadoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estadoProducto", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EstadoVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estadoVenta", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genero", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="JornadaLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jornadaLaboral", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metodoPago", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Nacionalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nacionalidad", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreRol", models.CharField(max_length=100)),
                ("descripcionRol", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TipoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipoContrato", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipoDocumento", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TipoMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipoMovimiento", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TipoPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipoPersona", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombrePersona", models.CharField(max_length=100)),
                ("apellidoPersona", models.CharField(max_length=100)),
                ("numeroDocumentoPersona", models.CharField(max_length=50)),
                ("direccionPersona", models.CharField(max_length=200)),
                ("telefonoPersona", models.CharField(max_length=20)),
                ("emailPersona", models.EmailField(max_length=254)),
                ("registroPersona", models.DateTimeField(auto_now_add=True)),
                (
                    "idEstado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.estado"
                    ),
                ),
                (
                    "idTipoDocumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.tipodocumento",
                    ),
                ),
                (
                    "idTipoPersona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.tipopersona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaNacimiento", models.DateField()),
                ("fechaContratacion", models.DateField()),
                (
                    "salarioEmpleado",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("epsEmpleado", models.CharField(max_length=100)),
                (
                    "fotoEmpleado",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_empleados/"
                    ),
                ),
                (
                    "idEstadoCivil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.estadocivil",
                    ),
                ),
                (
                    "idEstadoEmpleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.estadoempleado",
                    ),
                ),
                (
                    "idGenero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.genero"
                    ),
                ),
                (
                    "idJornadaLaboral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.jornadalaboral",
                    ),
                ),
                (
                    "idNacionalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.nacionalidad",
                    ),
                ),
                (
                    "idPersona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.persona"
                    ),
                ),
                (
                    "idTipoContrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.tipocontrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaRegistroCliente", models.DateTimeField(auto_now_add=True)),
                (
                    "idEstado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.estado"
                    ),
                ),
                (
                    "idPersona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.persona"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreProducto", models.CharField(max_length=100)),
                ("descripcionProducto", models.CharField(max_length=200)),
                ("stockProducto", models.PositiveBigIntegerField()),
                (
                    "precioProducto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("fechaIngresoProducto", models.DateTimeField(auto_now_add=True)),
                (
                    "fotoProducto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_productos/"
                    ),
                ),
                (
                    "idCategoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.categoria"
                    ),
                ),
                (
                    "idEstadoProducto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.estadoproducto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccionProveedor", models.CharField(max_length=200)),
                ("telefonoProveedor", models.CharField(max_length=20)),
                ("emailProveedor", models.EmailField(max_length=254)),
                ("fechaRegistroProveedor", models.DateTimeField(auto_now_add=True)),
                (
                    "idEstado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.estado"
                    ),
                ),
                (
                    "idPersona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.persona"
                    ),
                ),
                (
                    "idTipoPersona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.tipopersona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigoMovimiento", models.CharField(max_length=50)),
                (
                    "precioCompraUnidad",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precioVentaUnidad",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cantidadProductoMovimiento", models.PositiveBigIntegerField()),
                (
                    "totalValorMovimiento",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "observacionMovimiento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fechaMovimiento", models.DateTimeField(auto_now_add=True)),
                (
                    "idEmpleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.empleado"
                    ),
                ),
                (
                    "idProducto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.producto"
                    ),
                ),
                (
                    "idProveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.proveedor",
                    ),
                ),
                (
                    "tipoMovimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.tipomovimiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "totalValorVenta",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("fechaVenta", models.DateTimeField(auto_now_add=True)),
                (
                    "estadoVenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.estadoventa",
                    ),
                ),
                (
                    "idCliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.cliente"
                    ),
                ),
                (
                    "idEmpleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.empleado"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VentaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroCuotas", models.PositiveBigIntegerField()),
                ("valorCuota", models.DecimalField(decimal_places=2, max_digits=15)),
                ("fechaInicioCredito", models.DateTimeField(auto_now_add=True)),
                ("fechaFinCredito", models.DateTimeField()),
                ("interesCredito", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "saldoPendiente",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "EstadoCredito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.estadocredito",
                    ),
                ),
                (
                    "idVenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.venta"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VentaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidadProducto", models.PositiveBigIntegerField()),
                (
                    "precioVentaUnidad",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "subTotalValorProducto",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "descuentoProducto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "totalValorVenta",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "MetodoPago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUD.metodopago",
                    ),
                ),
                (
                    "idProducto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.producto"
                    ),
                ),
                (
                    "idVenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.venta"
                    ),
                ),
            ],
        ),
    ]
