# Generated by Django 5.2.5 on 2025-08-31 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('empleados', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoProducto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMovimiento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('descripcionProducto', models.CharField(max_length=200)),
                ('stockProducto', models.PositiveBigIntegerField()),
                ('precioProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaIngresoProducto', models.DateTimeField(auto_now_add=True)),
                ('fotoProducto', models.ImageField(blank=True, null=True, upload_to='uploads/fotos_productos/')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
                ('idEstadoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.estadoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccionProveedor', models.CharField(max_length=200)),
                ('telefonoProveedor', models.CharField(max_length=20)),
                ('emailProveedor', models.EmailField(max_length=254)),
                ('fechaRegistroProveedor', models.DateTimeField(auto_now_add=True)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
                ('idTipoPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.tipopersona')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoMovimiento', models.CharField(max_length=50)),
                ('precioCompraUnidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioVentaUnidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidadProductoMovimiento', models.PositiveBigIntegerField()),
                ('totalValorMovimiento', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observacionMovimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('fechaMovimiento', models.DateTimeField(auto_now_add=True)),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('idProveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.proveedor')),
                ('tipoMovimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipomovimiento')),
            ],
        ),
    ]
