# Generated by Django 5.2.5 on 2025-09-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotoProducto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_productos/'),
        ),
    ]
# Generated by Django 5.2.5 on 2025-09-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotoProducto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_productos/'),
        ),
    ]
