# Generated by Django 5.2.5 on 2025-09-01 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_fotoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(max_length=200, verbose_name='DescripcionProducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaIngresoProducto',
            field=models.DateTimeField(auto_now_add=True, verbose_name='FechaIngresoProducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fotoProducto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_productos/', verbose_name='FotoProducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idEstadoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.estadoproducto', verbose_name='EstadoProducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=100, verbose_name='NombreProducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PrecioProducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stockProducto',
            field=models.PositiveBigIntegerField(default=0, verbose_name='StockProducto'),
        ),
    ]
