# Generated by Django 5.2.5 on 2025-09-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_fotoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotoProducto',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/fotos_productos/'),
        ),
    ]
