# Generated by Django 5.2.5 on 2025-08-31 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistroCliente', models.DateTimeField(auto_now_add=True)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
        ),
    ]
