# Generated by Django 5.2.5 on 2025-09-01 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0003_alter_estado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idEstado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
    ]
