# Generated by Django 5.2.5 on 2025-08-31 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoCivil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPersona', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersona', models.CharField(max_length=100)),
                ('apellidoPersona', models.CharField(max_length=100)),
                ('numeroDocumentoPersona', models.CharField(max_length=50)),
                ('direccionPersona', models.CharField(max_length=200)),
                ('telefonoPersona', models.CharField(max_length=20)),
                ('emailPersona', models.EmailField(max_length=254)),
                ('registroPersona', models.DateTimeField(auto_now_add=True)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('idTipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.tipodocumento')),
                ('idTipoPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.tipopersona')),
            ],
        ),
    ]
