# Generated by Django 5.2.5 on 2025-09-01 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_idestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='idEstado',
        ),
        migrations.AddField(
            model_name='persona',
            name='idGenero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.genero'),
        ),
    ]
