# Generated by Django 5.2.5 on 2025-09-01 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_remove_persona_idestado_persona_idgenero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='idGenero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.genero'),
        ),
    ]
