# Generated by Django 5.2.5 on 2025-09-01 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_persona_idgenero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='Activo', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='idEstado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.estado'),
        ),
    ]
