# Generated by Django 5.2.5 on 2025-09-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_persona_idestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='idEstado',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
