# Generated by Django 5.2.5 on 2025-09-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_estado_estado'),
        ('personas', '0007_remove_persona_idestado_delete_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='idEstado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
    ]
